// Code generated by generator, DO NOT EDIT.
package sub

import uuid "github.com/google/uuid"

type ProductBuilder struct {
	product *Product
}

func NewProductBuilder() *ProductBuilder {
	return &ProductBuilder{}
}
func (b *ProductBuilder) WithID(iD uuid.UUID) *ProductBuilder {
	b.product.ID = iD
	return b
}
func (b *ProductBuilder) WithArticleNumber(articleNumber *string) *ProductBuilder {
	b.product.ArticleNumber = articleNumber
	return b
}
func (b *ProductBuilder) WithName(name string) *ProductBuilder {
	b.product.Name = name
	return b
}
func (b *ProductBuilder) WithDescription(description string) *ProductBuilder {
	b.product.Description = description
	return b
}
func (b *ProductBuilder) WithColor(color string) *ProductBuilder {
	b.product.Color = color
	return b
}
func (b *ProductBuilder) WithPippo(pippo *Whatever) *ProductBuilder {
	b.product.Pippo = pippo
	return b
}
func (b *ProductBuilder) WithSize(size string) *ProductBuilder {
	b.product.Size = size
	return b
}
func (b *ProductBuilder) WithStockAvailability(stockAvailability int) *ProductBuilder {
	b.product.StockAvailability = stockAvailability
	return b
}
func (b *ProductBuilder) WithPriceCents(priceCents int) *ProductBuilder {
	b.product.PriceCents = priceCents
	return b
}
func (b *ProductBuilder) WithOnSale(onSale bool) *ProductBuilder {
	b.product.OnSale = onSale
	return b
}
func (b *ProductBuilder) Build() *Product {
	return b.product
}
