// Code generated by generator, DO NOT EDIT.
package sub

type WhateverBuilder struct {
	whatever *Whatever
}

func NewWhateverBuilder() *WhateverBuilder {
	return &WhateverBuilder{}
}
func (b *WhateverBuilder) Build() *Whatever {
	return b.whatever
}
